### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by nandordudas** [nandordudas/build-todo-app#2]
### Clear and concise description

~~As a developer I want to use PostgreSQL in Devcontainer so add new service to Docker.~~

Requirements were imported in APP-3.

Acceptance criteria

- [x] APP-1 is done
- [x] create a simple schema for the ToDo application, insert the schema within a comment below - please use markdown syntax to highlighting
- [x] create queries for complete and incomplete todo items
- [x] create queries for the missing delete, insert and update operations too

### Additional context

APP-7 is depending on this.

:bulb: please be prepared that we should also use partial tasks - sub/parent todo, **the picture does not include it**.

Check [diagram].

Use [HeidiSQL] or [VS Code extension] for connecting to database if needed.

![ToDo application](https://user-images.githubusercontent.com/15153245/212686120-47d33248-1f68-4a80-a52b-9a073f783b53.png)

[diagram]: https://dbdiagram.io/d/63c53414296d97641d79ec12
[VS Code extension]: https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-postgresql-client2
[HeidiSQL]: https://www.heidisql.com/

**Comment by csaba-nagy** [comment]
I'm having issues connecting to the PostgreSQL database. If I put the following line to the docker-compose.yml file before the postgres service definition, it works fine, otherwise the database refuses the connection.
`network_mode: service:postgres`

Can you check this, please?

**Comment by csaba-nagy** [comment]
Here is the schema what I created:

**CREATE TABLE** `todos` (
`id` **SERIAL PRIMARY KEY**,
`title` **VARCHAR(32) NOT NULL**,
`created_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**,
`updated_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**
);

**CREATE TABLE** `statuses` (
`id` **SERIAL PRIMARY KEY**,
`title` **VARCHAR(32) NOT NULL UNIQUE**,
`created_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**,
`updated_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**
);


**CREATE TABLE** todo_status (
`todo_id` **INTEGER REFERENCES** `todos(id)` **ON DELETE CASCADE ON UPDATE CASCADE**,
`status_id` **INTEGER REFERENCES** `status(id)` **ON DELETE CASCADE ON UPDATE CASCADE**,
`updated_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**
);

**CREATE UNIQUE INDEX** `todo_status_unique_index` **ON** `todo_status(todo_id, status_id)`;

**Comment by nandordudas** [comment]
Why are you not using using composite unique index on `todo_status` instead of a composite primary key?

**Comment by csaba-nagy** [comment]
Good idea, I modified the original schema with your suggestion.

Here it is: 

**CREATE TABLE** `todos` (
`id` **SERIAL PRIMARY KEY**,
`title` **VARCHAR(32) NOT NULL**,
`created_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**,
`updated_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**
);

**CREATE TABLE** `statuses` (
`id` **SERIAL PRIMARY KEY**,
`title` **VARCHAR(32) NOT NULL UNIQUE**,
`created_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**,
`updated_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**
);

**CREATE TABLE** todo_status (
`todo_id` **INTEGER REFERENCES** `todos(id)` **ON DELETE CASCADE ON UPDATE CASCADE**,
`status_id` **INTEGER REFERENCES** `status(id)` **ON DELETE CASCADE ON UPDATE CASCADE**,
**PRIMARY KEY** (`status_id`, `todo_id`),
`updated_at` **TIMESTAMP WITH TIME ZONE DEFAULT (NOW())**
);

### If we want to set a parent/children relation between todos, then the following lines should be added to the schema:

**ALTER TABLE** `todos`
**ADD COLUMN** `parent_todo_id` **INTEGER REFERENCES** `todos(id)`;

### Also we can set a unique index for that, so a todo can have only one parent:

**CREATE UNIQUE INDEX** `parent_todo_id_unique_index` **ON** `todos(parent_todo)`;

**Comment by nandordudas** [comment]
It looks good and is a good example of parenting - the future will prove it.

**Comment by nandordudas** [comment]
I miss the explanation, you gave a good solution, but I also want to know the reason. Feel free to answer the questions.

Keep it simple and keep it going.

**Comment by csaba-nagy** [comment]
Actually, the unique key was my first idea. I thought, "the row should be unique, a task cannot have multiple statuses". So I just wrote it, I didn't think about it precisely.

**Comment by nandordudas** [comment]
thanks
